<?php

namespace App\Filament\Resources\Shop\CustomerResource\Pages;

use App\Filament\Resources\Shop\CustomerResource;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;

class ScanCustomer extends EditCustomer
{
    public function mount(int|string $record): void
    {
        parent::mount($record); // TODO: Change the autogenerated stub
    }

    protected function getActions(): array
    {
        return [
            Action::make('done')
                ->color('success')
                ->action(function ($record) {
                    $record->scan();
                })
            ,
            Actions\DeleteAction::make(),
            Actions\RestoreAction::make(),
            Actions\ForceDeleteAction::make(),
        ];
    }
}
